package pe.dido.svr.reqmngt.model;

import java.io.Serializable;

public class Dept implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dept
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer deptId;
	private Integer motherDeptId;
	private String deptNm;
	private String deptDc;
	public Integer getDeptId() {
		return deptId;
	}
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}
	public Integer getMotherDeptId() {
		return motherDeptId;
	}
	public void setMotherDeptId(Integer motherDeptId) {
		this.motherDeptId = motherDeptId;
	}
	public String getDeptNm() {
		return deptNm;
	}
	public void setDeptNm(String deptNm) {
		this.deptNm = deptNm;
	}
	public String getDeptDc() {
		return deptDc;
	}
	public void setDeptDc(String deptDc) {
		this.deptDc = deptDc;
	}

}