package pe.dido.svr.reqmngt.model;

import java.io.Serializable;

public class Dept implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dept
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.DEPT_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String deptDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.DEPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.DEPT_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String deptNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dept.MOTHER_DEPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer motherDeptId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Dept other = (Dept) that;
		return (this.getDeptId() == null ? other.getDeptId() == null : this
				.getDeptId().equals(other.getDeptId()))
				&& (this.getMotherDeptId() == null ? other.getMotherDeptId() == null
						: this.getMotherDeptId()
								.equals(other.getMotherDeptId()))
				&& (this.getDeptNm() == null ? other.getDeptNm() == null : this
						.getDeptNm().equals(other.getDeptNm()))
				&& (this.getDeptDc() == null ? other.getDeptDc() == null : this
						.getDeptDc().equals(other.getDeptDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.DEPT_DC
	 * @return  the value of dept.DEPT_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDeptDc() {
		return deptDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.DEPT_ID
	 * @return  the value of dept.DEPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.DEPT_NM
	 * @return  the value of dept.DEPT_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDeptNm() {
		return deptNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dept.MOTHER_DEPT_ID
	 * @return  the value of dept.MOTHER_DEPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getMotherDeptId() {
		return motherDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getDeptId() == null) ? 0 : getDeptId().hashCode());
		result = prime
				* result
				+ ((getMotherDeptId() == null) ? 0 : getMotherDeptId()
						.hashCode());
		result = prime * result
				+ ((getDeptNm() == null) ? 0 : getDeptNm().hashCode());
		result = prime * result
				+ ((getDeptDc() == null) ? 0 : getDeptDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.DEPT_DC
	 * @param deptDc  the value for dept.DEPT_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDeptDc(String deptDc) {
		this.deptDc = deptDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.DEPT_ID
	 * @param deptId  the value for dept.DEPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.DEPT_NM
	 * @param deptNm  the value for dept.DEPT_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDeptNm(String deptNm) {
		this.deptNm = deptNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dept.MOTHER_DEPT_ID
	 * @param motherDeptId  the value for dept.MOTHER_DEPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setMotherDeptId(Integer motherDeptId) {
		this.motherDeptId = motherDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dept
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", deptId=").append(deptId);
		sb.append(", motherDeptId=").append(motherDeptId);
		sb.append(", deptNm=").append(deptNm);
		sb.append(", deptDc=").append(deptDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}