package pe.dido.svr.reqmngt.model;

import java.io.Serializable;

public class DmndRelateBasis implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dmnd_relate_basis
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dmnd_relate_basis.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dmnd_relate_basis.RELATE_BASIS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer relateBasisId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dmnd_relate_basis.RELATE_BASIS_ORIGIN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String relateBasisOrigin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dmnd_relate_basis.RELATE_BASIS_SJ
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String relateBasisSj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dmnd_relate_basis.UPPER_DMND_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer upperDmndId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dmnd_relate_basis
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		DmndRelateBasis other = (DmndRelateBasis) that;
		return (this.getRelateBasisId() == null ? other.getRelateBasisId() == null
				: this.getRelateBasisId().equals(other.getRelateBasisId()))
				&& (this.getUpperDmndId() == null ? other.getUpperDmndId() == null
						: this.getUpperDmndId().equals(other.getUpperDmndId()))
				&& (this.getRelateBasisSj() == null ? other.getRelateBasisSj() == null
						: this.getRelateBasisSj().equals(
								other.getRelateBasisSj()))
				&& (this.getRelateBasisOrigin() == null ? other
						.getRelateBasisOrigin() == null : this
						.getRelateBasisOrigin().equals(
								other.getRelateBasisOrigin()))
				&& (this.getDc() == null ? other.getDc() == null : this.getDc()
						.equals(other.getDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dmnd_relate_basis.DC
	 * @return  the value of dmnd_relate_basis.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDc() {
		return dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dmnd_relate_basis.RELATE_BASIS_ID
	 * @return  the value of dmnd_relate_basis.RELATE_BASIS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getRelateBasisId() {
		return relateBasisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dmnd_relate_basis.RELATE_BASIS_ORIGIN
	 * @return  the value of dmnd_relate_basis.RELATE_BASIS_ORIGIN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getRelateBasisOrigin() {
		return relateBasisOrigin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dmnd_relate_basis.RELATE_BASIS_SJ
	 * @return  the value of dmnd_relate_basis.RELATE_BASIS_SJ
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getRelateBasisSj() {
		return relateBasisSj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dmnd_relate_basis.UPPER_DMND_ID
	 * @return  the value of dmnd_relate_basis.UPPER_DMND_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getUpperDmndId() {
		return upperDmndId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dmnd_relate_basis
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((getRelateBasisId() == null) ? 0 : getRelateBasisId()
						.hashCode());
		result = prime
				* result
				+ ((getUpperDmndId() == null) ? 0 : getUpperDmndId().hashCode());
		result = prime
				* result
				+ ((getRelateBasisSj() == null) ? 0 : getRelateBasisSj()
						.hashCode());
		result = prime
				* result
				+ ((getRelateBasisOrigin() == null) ? 0
						: getRelateBasisOrigin().hashCode());
		result = prime * result + ((getDc() == null) ? 0 : getDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dmnd_relate_basis.DC
	 * @param dc  the value for dmnd_relate_basis.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDc(String dc) {
		this.dc = dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dmnd_relate_basis.RELATE_BASIS_ID
	 * @param relateBasisId  the value for dmnd_relate_basis.RELATE_BASIS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setRelateBasisId(Integer relateBasisId) {
		this.relateBasisId = relateBasisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dmnd_relate_basis.RELATE_BASIS_ORIGIN
	 * @param relateBasisOrigin  the value for dmnd_relate_basis.RELATE_BASIS_ORIGIN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setRelateBasisOrigin(String relateBasisOrigin) {
		this.relateBasisOrigin = relateBasisOrigin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dmnd_relate_basis.RELATE_BASIS_SJ
	 * @param relateBasisSj  the value for dmnd_relate_basis.RELATE_BASIS_SJ
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setRelateBasisSj(String relateBasisSj) {
		this.relateBasisSj = relateBasisSj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dmnd_relate_basis.UPPER_DMND_ID
	 * @param upperDmndId  the value for dmnd_relate_basis.UPPER_DMND_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setUpperDmndId(Integer upperDmndId) {
		this.upperDmndId = upperDmndId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dmnd_relate_basis
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", relateBasisId=").append(relateBasisId);
		sb.append(", upperDmndId=").append(upperDmndId);
		sb.append(", relateBasisSj=").append(relateBasisSj);
		sb.append(", relateBasisOrigin=").append(relateBasisOrigin);
		sb.append(", dc=").append(dc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}