package pe.dido.svr.reqmngt.model;

import java.io.Serializable;

public class DmndRelateBasis implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dmnd_relate_basis
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer relateBasisId;
	private Integer upperDmndId;
	private String relateBasisSj;
	private String relateBasisOrigin;
	private String dc;
	public Integer getRelateBasisId() {
		return relateBasisId;
	}
	public void setRelateBasisId(Integer relateBasisId) {
		this.relateBasisId = relateBasisId;
	}
	public Integer getUpperDmndId() {
		return upperDmndId;
	}
	public void setUpperDmndId(Integer upperDmndId) {
		this.upperDmndId = upperDmndId;
	}
	public String getRelateBasisSj() {
		return relateBasisSj;
	}
	public void setRelateBasisSj(String relateBasisSj) {
		this.relateBasisSj = relateBasisSj;
	}
	public String getRelateBasisOrigin() {
		return relateBasisOrigin;
	}
	public void setRelateBasisOrigin(String relateBasisOrigin) {
		this.relateBasisOrigin = relateBasisOrigin;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}

}