package pe.dido.svr.reqmngt.model;

import java.io.Serializable;

public class UpperDmnd implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table upper_dmnd
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer upperDmndId;
	private String upperDmndIdntfr;
	private String upperDmndNm;
	private String dc;
	public Integer getUpperDmndId() {
		return upperDmndId;
	}
	public void setUpperDmndId(Integer upperDmndId) {
		this.upperDmndId = upperDmndId;
	}
	public String getUpperDmndIdntfr() {
		return upperDmndIdntfr;
	}
	public void setUpperDmndIdntfr(String upperDmndIdntfr) {
		this.upperDmndIdntfr = upperDmndIdntfr;
	}
	public String getUpperDmndNm() {
		return upperDmndNm;
	}
	public void setUpperDmndNm(String upperDmndNm) {
		this.upperDmndNm = upperDmndNm;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}

}