package pe.dido.svr.reqmngt.model;

import java.io.Serializable;

public class UpperDmnd implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table upper_dmnd
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upper_dmnd.UPPER_DMND_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer upperDmndId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column upper_dmnd.UPPER_DMND_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String upperDmndIdntfr;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upper_dmnd
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UpperDmnd other = (UpperDmnd) that;
		return (this.getUpperDmndId() == null ? other.getUpperDmndId() == null
				: this.getUpperDmndId().equals(other.getUpperDmndId()))
				&& (this.getUpperDmndIdntfr() == null ? other
						.getUpperDmndIdntfr() == null : this
						.getUpperDmndIdntfr()
						.equals(other.getUpperDmndIdntfr()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upper_dmnd.UPPER_DMND_ID
	 * @return  the value of upper_dmnd.UPPER_DMND_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getUpperDmndId() {
		return upperDmndId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column upper_dmnd.UPPER_DMND_IDNTFR
	 * @return  the value of upper_dmnd.UPPER_DMND_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getUpperDmndIdntfr() {
		return upperDmndIdntfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upper_dmnd
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((getUpperDmndId() == null) ? 0 : getUpperDmndId().hashCode());
		result = prime
				* result
				+ ((getUpperDmndIdntfr() == null) ? 0 : getUpperDmndIdntfr()
						.hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upper_dmnd.UPPER_DMND_ID
	 * @param upperDmndId  the value for upper_dmnd.UPPER_DMND_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setUpperDmndId(Integer upperDmndId) {
		this.upperDmndId = upperDmndId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column upper_dmnd.UPPER_DMND_IDNTFR
	 * @param upperDmndIdntfr  the value for upper_dmnd.UPPER_DMND_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setUpperDmndIdntfr(String upperDmndIdntfr) {
		this.upperDmndIdntfr = upperDmndIdntfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table upper_dmnd
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", upperDmndId=").append(upperDmndId);
		sb.append(", upperDmndIdntfr=").append(upperDmndIdntfr);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}