package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompInnerClassAttrb implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_inner_class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.ATRB_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer atrbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.ATTRB_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String attrbNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.BASS_VALUE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bassValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.COMPN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer compnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.INNER_CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer innerClassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String ty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_attrb.VISIBLTY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String visiblty;

	/**
	 * @return the atrbId
	 */
	public Integer getAtrbId() {
		return atrbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_attrb.ATTRB_NM
	 * @return  the value of comp_inner_class_attrb.ATTRB_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getAttrbNm() {
		return attrbNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_attrb.BASS_VALUE
	 * @return  the value of comp_inner_class_attrb.BASS_VALUE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBassValue() {
		return bassValue;
	}

	/**
	 * @return the compnId
	 */
	public Integer getCompnId() {
		return compnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_attrb.DC
	 * @return  the value of comp_inner_class_attrb.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDc() {
		return dc;
	}

	/**
	 * @return the innerClassId
	 */
	public Integer getInnerClassId() {
		return innerClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_attrb.TY
	 * @return  the value of comp_inner_class_attrb.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTy() {
		return ty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_attrb.VISIBLTY
	 * @return  the value of comp_inner_class_attrb.VISIBLTY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getVisiblty() {
		return visiblty;
	}

	/**
	 * @param atrbId the atrbId to set
	 */
	public void setAtrbId(Integer atrbId) {
		this.atrbId = atrbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_attrb.ATTRB_NM
	 * @param attrbNm  the value for comp_inner_class_attrb.ATTRB_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setAttrbNm(String attrbNm) {
		this.attrbNm = attrbNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_attrb.BASS_VALUE
	 * @param bassValue  the value for comp_inner_class_attrb.BASS_VALUE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBassValue(String bassValue) {
		this.bassValue = bassValue;
	}

	/**
	 * @param compnId the compnId to set
	 */
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_attrb.DC
	 * @param dc  the value for comp_inner_class_attrb.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDc(String dc) {
		this.dc = dc;
	}

	/**
	 * @param innerClassId the innerClassId to set
	 */
	public void setInnerClassId(Integer innerClassId) {
		this.innerClassId = innerClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_attrb.TY
	 * @param ty  the value for comp_inner_class_attrb.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTy(String ty) {
		this.ty = ty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_attrb.VISIBLTY
	 * @param visiblty  the value for comp_inner_class_attrb.VISIBLTY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setVisiblty(String visiblty) {
		this.visiblty = visiblty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_inner_class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", attrbNm=").append(attrbNm);
		sb.append(", visiblty=").append(visiblty);
		sb.append(", ty=").append(ty);
		sb.append(", bassValue=").append(bassValue);
		sb.append(", dc=").append(dc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

}