package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompIfclass implements Serializable {
	public Integer getCompnId() {
		return compnId;
	}
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}
	public Integer getIfOprtinId() {
		return ifOprtinId;
	}
	public void setIfOprtinId(Integer ifOprtinId) {
		this.ifOprtinId = ifOprtinId;
	}
	public String getIfOprtinNm() {
		return ifOprtinNm;
	}
	public void setIfOprtinNm(String ifOprtinNm) {
		this.ifOprtinNm = ifOprtinNm;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_ifclass
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer compnId;
	private Integer ifOprtinId;
	private String ifOprtinNm;
	private String dc;
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}