package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompInnerClassOp implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_inner_class_op
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.COMPN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer compnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.INNER_CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer innerClassId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.OPRTIN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer oprtinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.OPRTIN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String oprtinNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.PARAMTR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String paramtrDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.PARAMTR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String paramtrNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.RETURN_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String returnTy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_inner_class_op.SCOPE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String scope;

	/**
	 * @return the compnId
	 */
	public Integer getCompnId() {
		return compnId;
	}

	/**
	 * @return the dc
	 */
	public String getDc() {
		return dc;
	}

	/**
	 * @return the innerClassId
	 */
	public Integer getInnerClassId() {
		return innerClassId;
	}

	/**
	 * @return the oprtinId
	 */
	public Integer getOprtinId() {
		return oprtinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_op.OPRTIN_NM
	 * @return  the value of comp_inner_class_op.OPRTIN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getOprtinNm() {
		return oprtinNm;
	}

	/**
	 * @return the paramtrDc
	 */
	public String getParamtrDc() {
		return paramtrDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_op.PARAMTR_NM
	 * @return  the value of comp_inner_class_op.PARAMTR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getParamtrNm() {
		return paramtrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_op.RETURN_TY
	 * @return  the value of comp_inner_class_op.RETURN_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getReturnTy() {
		return returnTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_inner_class_op.SCOPE
	 * @return  the value of comp_inner_class_op.SCOPE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getScope() {
		return scope;
	}

	/**
	 * @param compnId the compnId to set
	 */
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}

	/**
	 * @param dc the dc to set
	 */
	public void setDc(String dc) {
		this.dc = dc;
	}

	/**
	 * @param innerClassId the innerClassId to set
	 */
	public void setInnerClassId(Integer innerClassId) {
		this.innerClassId = innerClassId;
	}

	/**
	 * @param oprtinId the oprtinId to set
	 */
	public void setOprtinId(Integer oprtinId) {
		this.oprtinId = oprtinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_op.OPRTIN_NM
	 * @param oprtinNm  the value for comp_inner_class_op.OPRTIN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setOprtinNm(String oprtinNm) {
		this.oprtinNm = oprtinNm;
	}

	/**
	 * @param paramtrDc the paramtrDc to set
	 */
	public void setParamtrDc(String paramtrDc) {
		this.paramtrDc = paramtrDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_op.PARAMTR_NM
	 * @param paramtrNm  the value for comp_inner_class_op.PARAMTR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setParamtrNm(String paramtrNm) {
		this.paramtrNm = paramtrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_op.RETURN_TY
	 * @param returnTy  the value for comp_inner_class_op.RETURN_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setReturnTy(String returnTy) {
		this.returnTy = returnTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_inner_class_op.SCOPE
	 * @param scope  the value for comp_inner_class_op.SCOPE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScope(String scope) {
		this.scope = scope;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_inner_class_op
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", oprtinNm=").append(oprtinNm);
		sb.append(", scope=").append(scope);
		sb.append(", returnTy=").append(returnTy);
		sb.append(", paramtrNm=").append(paramtrNm);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

}