package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompInnerClassAttrb implements Serializable {
	public Integer getAtrbId() {
		return atrbId;
	}
	public void setAtrbId(Integer atrbId) {
		this.atrbId = atrbId;
	}
	public Integer getInnerClassId() {
		return innerClassId;
	}
	public void setInnerClassId(Integer innerClassId) {
		this.innerClassId = innerClassId;
	}
	public Integer getCompnId() {
		return compnId;
	}
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}
	public String getAttrbNm() {
		return attrbNm;
	}
	public void setAttrbNm(String attrbNm) {
		this.attrbNm = attrbNm;
	}
	public String getVisiblty() {
		return visiblty;
	}
	public void setVisiblty(String visiblty) {
		this.visiblty = visiblty;
	}
	public String getTy() {
		return ty;
	}
	public void setTy(String ty) {
		this.ty = ty;
	}
	public String getBassValue() {
		return bassValue;
	}
	public void setBassValue(String bassValue) {
		this.bassValue = bassValue;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_inner_class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer atrbId;
	private Integer innerClassId;
	private Integer compnId;
	private String attrbNm;
	private String visiblty;
	private String ty;
	private String bassValue;
	private String dc;

	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}