package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompImplClass implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_impl_class
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_impl_class.COMPN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer compnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_impl_class.EMBD_CLASS_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String embdClassDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_impl_class.EMBD_CLASS_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String embdClassNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_impl_class.INNER_CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer innerClassId;

	/**
	 * @return the compnId
	 */
	public Integer getCompnId() {
		return compnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_impl_class.EMBD_CLASS_DC
	 * @return  the value of comp_impl_class.EMBD_CLASS_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getEmbdClassDc() {
		return embdClassDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_impl_class.EMBD_CLASS_NM
	 * @return  the value of comp_impl_class.EMBD_CLASS_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getEmbdClassNm() {
		return embdClassNm;
	}

	/**
	 * @return the innerClassId
	 */
	public Integer getInnerClassId() {
		return innerClassId;
	}

	/**
	 * @param compnId the compnId to set
	 */
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_impl_class.EMBD_CLASS_DC
	 * @param embdClassDc  the value for comp_impl_class.EMBD_CLASS_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setEmbdClassDc(String embdClassDc) {
		this.embdClassDc = embdClassDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_impl_class.EMBD_CLASS_NM
	 * @param embdClassNm  the value for comp_impl_class.EMBD_CLASS_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setEmbdClassNm(String embdClassNm) {
		this.embdClassNm = embdClassNm;
	}

	/**
	 * @param innerClassId the innerClassId to set
	 */
	public void setInnerClassId(Integer innerClassId) {
		this.innerClassId = innerClassId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_impl_class
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", embdClassNm=").append(embdClassNm);
		sb.append(", embdClassDc=").append(embdClassDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

}