package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompM implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_m.COMPN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer compnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_m.COMPN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String compnNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comp_m.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dc;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		CompM other = (CompM) that;
		return (this.getCompnId() == null ? other.getCompnId() == null : this
				.getCompnId().equals(other.getCompnId()))
				&& (this.getCompnNm() == null ? other.getCompnNm() == null
						: this.getCompnNm().equals(other.getCompnNm()))
				&& (this.getDc() == null ? other.getDc() == null : this.getDc()
						.equals(other.getDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_m.COMPN_ID
	 * @return  the value of comp_m.COMPN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getCompnId() {
		return compnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_m.COMPN_NM
	 * @return  the value of comp_m.COMPN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCompnNm() {
		return compnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comp_m.DC
	 * @return  the value of comp_m.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDc() {
		return dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getCompnId() == null) ? 0 : getCompnId().hashCode());
		result = prime * result
				+ ((getCompnNm() == null) ? 0 : getCompnNm().hashCode());
		result = prime * result + ((getDc() == null) ? 0 : getDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_m.COMPN_ID
	 * @param compnId  the value for comp_m.COMPN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_m.COMPN_NM
	 * @param compnNm  the value for comp_m.COMPN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCompnNm(String compnNm) {
		this.compnNm = compnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comp_m.DC
	 * @param dc  the value for comp_m.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDc(String dc) {
		this.dc = dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comp_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", compnId=").append(compnId);
		sb.append(", compnNm=").append(compnNm);
		sb.append(", dc=").append(dc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}