package pe.dido.svr.compmodeling.model;

import java.io.Serializable;

public class CompM implements Serializable {
	public Integer getCompnId() {
		return compnId;
	}
	public void setCompnId(Integer compnId) {
		this.compnId = compnId;
	}
	public String getCompnNm() {
		return compnNm;
	}
	public void setCompnNm(String compnNm) {
		this.compnNm = compnNm;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table comp_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer compnId;
	private String compnNm;
	private String dc;

}