package pe.dido.svr.compmodeling.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class UdaCluster implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uda_cluster
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;

	private Integer ucId;
	private Integer classEnNm;
	private String grad;
	private Float acces_value;
	private Float wghtval;
	private String compnYy;
	private String compnNm;
	public Integer getUcId() {
		return ucId;
	}
	public void setUcId(Integer ucId) {
		this.ucId = ucId;
	}
	public Integer getClassEnNm() {
		return classEnNm;
	}
	public void setClassEnNm(Integer classEnNm) {
		this.classEnNm = classEnNm;
	}
	public String getGrad() {
		return grad;
	}
	public void setGrad(String grad) {
		this.grad = grad;
	}
	public Float getAcces_value() {
		return acces_value;
	}
	public void setAcces_value(Float acces_value) {
		this.acces_value = acces_value;
	}
	public Float getWghtval() {
		return wghtval;
	}
	public void setWghtval(Float wghtval) {
		this.wghtval = wghtval;
	}
	public String getCompnYy() {
		return compnYy;
	}
	public void setCompnYy(String compnYy) {
		this.compnYy = compnYy;
	}
	public String getCompnNm() {
		return compnNm;
	}
	public void setCompnNm(String compnNm) {
		this.compnNm = compnNm;
	}


}