package pe.dido.svr.clzmodeling.model;

import java.io.Serializable;

public class ClassM implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	public Integer getClassId() {
		return classId;
	}
	public void setClassId(Integer classId) {
		this.classId = classId;
	}
	public String getClassEnNm() {
		return classEnNm;
	}
	public void setClassEnNm(String classEnNm) {
		this.classEnNm = classEnNm;
	}
	public String getClassKrNm() {
		return classKrNm;
	}
	public void setClassKrNm(String classKrNm) {
		this.classKrNm = classKrNm;
	}
	public String getClassTy() {
		return classTy;
	}
	public void setClassTy(String classTy) {
		this.classTy = classTy;
	}
	public String getIdntfcOfficTy() {
		return idntfcOfficTy;
	}
	public void setIdntfcOfficTy(String idntfcOfficTy) {
		this.idntfcOfficTy = idntfcOfficTy;
	}
	public Integer getIdntfcOfficId() {
		return idntfcOfficId;
	}
	public void setIdntfcOfficId(Integer idntfcOfficId) {
		this.idntfcOfficId = idntfcOfficId;
	}
	private Integer classId;
	private String classEnNm;
	private String classKrNm;
	private String classTy;
	private String idntfcOfficTy;
	private Integer idntfcOfficId;
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}