package pe.dido.svr.clzmodeling.model;

import java.io.Serializable;

public class ClassM implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_m.CLASS_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String classEnNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_m.CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_m.CLASS_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String classKrNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_m.CLASS_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String classTy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_m.IDNTFC_OFFIC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer idntfcOfficId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_m.IDNTFC_OFFIC_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String idntfcOfficTy;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ClassM other = (ClassM) that;
		return (this.getClassId() == null ? other.getClassId() == null : this
				.getClassId().equals(other.getClassId()))
				&& (this.getClassEnNm() == null ? other.getClassEnNm() == null
						: this.getClassEnNm().equals(other.getClassEnNm()))
				&& (this.getClassKrNm() == null ? other.getClassKrNm() == null
						: this.getClassKrNm().equals(other.getClassKrNm()))
				&& (this.getClassTy() == null ? other.getClassTy() == null
						: this.getClassTy().equals(other.getClassTy()))
				&& (this.getIdntfcOfficTy() == null ? other.getIdntfcOfficTy() == null
						: this.getIdntfcOfficTy().equals(
								other.getIdntfcOfficTy()))
				&& (this.getIdntfcOfficId() == null ? other.getIdntfcOfficId() == null
						: this.getIdntfcOfficId().equals(
								other.getIdntfcOfficId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_m.CLASS_EN_NM
	 * @return  the value of class_m.CLASS_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getClassEnNm() {
		return classEnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_m.CLASS_ID
	 * @return  the value of class_m.CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_m.CLASS_KR_NM
	 * @return  the value of class_m.CLASS_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getClassKrNm() {
		return classKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_m.CLASS_TY
	 * @return  the value of class_m.CLASS_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getClassTy() {
		return classTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_m.IDNTFC_OFFIC_ID
	 * @return  the value of class_m.IDNTFC_OFFIC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getIdntfcOfficId() {
		return idntfcOfficId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_m.IDNTFC_OFFIC_TY
	 * @return  the value of class_m.IDNTFC_OFFIC_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getIdntfcOfficTy() {
		return idntfcOfficTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getClassId() == null) ? 0 : getClassId().hashCode());
		result = prime * result
				+ ((getClassEnNm() == null) ? 0 : getClassEnNm().hashCode());
		result = prime * result
				+ ((getClassKrNm() == null) ? 0 : getClassKrNm().hashCode());
		result = prime * result
				+ ((getClassTy() == null) ? 0 : getClassTy().hashCode());
		result = prime
				* result
				+ ((getIdntfcOfficTy() == null) ? 0 : getIdntfcOfficTy()
						.hashCode());
		result = prime
				* result
				+ ((getIdntfcOfficId() == null) ? 0 : getIdntfcOfficId()
						.hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_m.CLASS_EN_NM
	 * @param classEnNm  the value for class_m.CLASS_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setClassEnNm(String classEnNm) {
		this.classEnNm = classEnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_m.CLASS_ID
	 * @param classId  the value for class_m.CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_m.CLASS_KR_NM
	 * @param classKrNm  the value for class_m.CLASS_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setClassKrNm(String classKrNm) {
		this.classKrNm = classKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_m.CLASS_TY
	 * @param classTy  the value for class_m.CLASS_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setClassTy(String classTy) {
		this.classTy = classTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_m.IDNTFC_OFFIC_ID
	 * @param idntfcOfficId  the value for class_m.IDNTFC_OFFIC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIdntfcOfficId(Integer idntfcOfficId) {
		this.idntfcOfficId = idntfcOfficId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_m.IDNTFC_OFFIC_TY
	 * @param idntfcOfficTy  the value for class_m.IDNTFC_OFFIC_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIdntfcOfficTy(String idntfcOfficTy) {
		this.idntfcOfficTy = idntfcOfficTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", classId=").append(classId);
		sb.append(", classEnNm=").append(classEnNm);
		sb.append(", classKrNm=").append(classKrNm);
		sb.append(", classTy=").append(classTy);
		sb.append(", idntfcOfficTy=").append(idntfcOfficTy);
		sb.append(", idntfcOfficId=").append(idntfcOfficId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}