package pe.dido.svr.clzmodeling.model;

import java.io.Serializable;

public class ClassAttrb implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.ATRB_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer atrbId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.ATTRB_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String attrbEnNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.ATTRB_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String attrbKrNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.BASS_VALUE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bassValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.CLASS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer classId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.IEM_ATRB
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String iemAtrb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String ty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class_attrb.VISIBLTY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String visiblty;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		ClassAttrb other = (ClassAttrb) that;
		return (this.getAtrbId() == null ? other.getAtrbId() == null : this
				.getAtrbId().equals(other.getAtrbId()))
				&& (this.getClassId() == null ? other.getClassId() == null
						: this.getClassId().equals(other.getClassId()))
				&& (this.getAttrbEnNm() == null ? other.getAttrbEnNm() == null
						: this.getAttrbEnNm().equals(other.getAttrbEnNm()))
				&& (this.getAttrbKrNm() == null ? other.getAttrbKrNm() == null
						: this.getAttrbKrNm().equals(other.getAttrbKrNm()))
				&& (this.getVisiblty() == null ? other.getVisiblty() == null
						: this.getVisiblty().equals(other.getVisiblty()))
				&& (this.getTy() == null ? other.getTy() == null : this.getTy()
						.equals(other.getTy()))
				&& (this.getBassValue() == null ? other.getBassValue() == null
						: this.getBassValue().equals(other.getBassValue()))
				&& (this.getIemAtrb() == null ? other.getIemAtrb() == null
						: this.getIemAtrb().equals(other.getIemAtrb()))
				&& (this.getDc() == null ? other.getDc() == null : this.getDc()
						.equals(other.getDc()));
	}

	/**
	 * @return the atrbId
	 */
	public Integer getAtrbId() {
		return atrbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.ATTRB_EN_NM
	 * @return  the value of class_attrb.ATTRB_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getAttrbEnNm() {
		return attrbEnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.ATTRB_KR_NM
	 * @return  the value of class_attrb.ATTRB_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getAttrbKrNm() {
		return attrbKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.BASS_VALUE
	 * @return  the value of class_attrb.BASS_VALUE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBassValue() {
		return bassValue;
	}

	/**
	 * @return the classId
	 */
	public Integer getClassId() {
		return classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.DC
	 * @return  the value of class_attrb.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDc() {
		return dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.IEM_ATRB
	 * @return  the value of class_attrb.IEM_ATRB
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getIemAtrb() {
		return iemAtrb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.TY
	 * @return  the value of class_attrb.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTy() {
		return ty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class_attrb.VISIBLTY
	 * @return  the value of class_attrb.VISIBLTY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getVisiblty() {
		return visiblty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getAtrbId() == null) ? 0 : getAtrbId().hashCode());
		result = prime * result
				+ ((getClassId() == null) ? 0 : getClassId().hashCode());
		result = prime * result
				+ ((getAttrbEnNm() == null) ? 0 : getAttrbEnNm().hashCode());
		result = prime * result
				+ ((getAttrbKrNm() == null) ? 0 : getAttrbKrNm().hashCode());
		result = prime * result
				+ ((getVisiblty() == null) ? 0 : getVisiblty().hashCode());
		result = prime * result + ((getTy() == null) ? 0 : getTy().hashCode());
		result = prime * result
				+ ((getBassValue() == null) ? 0 : getBassValue().hashCode());
		result = prime * result
				+ ((getIemAtrb() == null) ? 0 : getIemAtrb().hashCode());
		result = prime * result + ((getDc() == null) ? 0 : getDc().hashCode());
		return result;
	}

	/**
	 * @param atrbId the atrbId to set
	 */
	public void setAtrbId(Integer atrbId) {
		this.atrbId = atrbId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.ATTRB_EN_NM
	 * @param attrbEnNm  the value for class_attrb.ATTRB_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setAttrbEnNm(String attrbEnNm) {
		this.attrbEnNm = attrbEnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.ATTRB_KR_NM
	 * @param attrbKrNm  the value for class_attrb.ATTRB_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setAttrbKrNm(String attrbKrNm) {
		this.attrbKrNm = attrbKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.BASS_VALUE
	 * @param bassValue  the value for class_attrb.BASS_VALUE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBassValue(String bassValue) {
		this.bassValue = bassValue;
	}

	/**
	 * @param classId the classId to set
	 */
	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.DC
	 * @param dc  the value for class_attrb.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDc(String dc) {
		this.dc = dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.IEM_ATRB
	 * @param iemAtrb  the value for class_attrb.IEM_ATRB
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIemAtrb(String iemAtrb) {
		this.iemAtrb = iemAtrb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.TY
	 * @param ty  the value for class_attrb.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTy(String ty) {
		this.ty = ty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class_attrb.VISIBLTY
	 * @param visiblty  the value for class_attrb.VISIBLTY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setVisiblty(String visiblty) {
		this.visiblty = visiblty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", attrbEnNm=").append(attrbEnNm);
		sb.append(", attrbKrNm=").append(attrbKrNm);
		sb.append(", visiblty=").append(visiblty);
		sb.append(", ty=").append(ty);
		sb.append(", bassValue=").append(bassValue);
		sb.append(", iemAtrb=").append(iemAtrb);
		sb.append(", dc=").append(dc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}