package pe.dido.svr.clzmodeling.model;

import java.io.Serializable;

public class ClassAttrb implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_attrb
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	private Integer atrbId;
	private Integer classId;
	private String attrbEnNm;
	private String attrbKrNm;
	private String visiblty;
	private String ty;
	private String bassValue;
	private String dc;
	private String iemAtrb;
	public Integer getAtrbId() {
		return atrbId;
	}
	public void setAtrbId(Integer atrbId) {
		this.atrbId = atrbId;
	}
	public Integer getClassId() {
		return classId;
	}
	public void setClassId(Integer classId) {
		this.classId = classId;
	}
	public String getAttrbEnNm() {
		return attrbEnNm;
	}
	public void setAttrbEnNm(String attrbEnNm) {
		this.attrbEnNm = attrbEnNm;
	}
	public String getAttrbKrNm() {
		return attrbKrNm;
	}
	public void setAttrbKrNm(String attrbKrNm) {
		this.attrbKrNm = attrbKrNm;
	}
	public String getVisiblty() {
		return visiblty;
	}
	public void setVisiblty(String visiblty) {
		this.visiblty = visiblty;
	}
	public String getTy() {
		return ty;
	}
	public void setTy(String ty) {
		this.ty = ty;
	}
	public String getBassValue() {
		return bassValue;
	}
	public void setBassValue(String bassValue) {
		this.bassValue = bassValue;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}
	public String getIemAtrb() {
		return iemAtrb;
	}
	public void setIemAtrb(String iemAtrb) {
		this.iemAtrb = iemAtrb;
	}
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}