package pe.dido.svr.clzmodeling.model;

import java.io.Serializable;

public class ClassOp implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class_op
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer oprtinId;
	private Integer classId;
	private String opEnNm;
	private String opKrNm;
	private String visiblty;
	private String returnTy;
	private String parmNm;
	private String parmDc;
	private String dc;
	public Integer getOprtinId() {
		return oprtinId;
	}
	public void setOprtinId(Integer oprtinId) {
		this.oprtinId = oprtinId;
	}
	public Integer getClassId() {
		return classId;
	}
	public void setClassId(Integer classId) {
		this.classId = classId;
	}
	public String getOpEnNm() {
		return opEnNm;
	}
	public void setOpEnNm(String opEnNm) {
		this.opEnNm = opEnNm;
	}
	public String getOpKrNm() {
		return opKrNm;
	}
	public void setOpKrNm(String opKrNm) {
		this.opKrNm = opKrNm;
	}
	public String getVisiblty() {
		return visiblty;
	}
	public void setVisiblty(String visiblty) {
		this.visiblty = visiblty;
	}
	public String getReturnTy() {
		return returnTy;
	}
	public void setReturnTy(String returnTy) {
		this.returnTy = returnTy;
	}
	public String getParmNm() {
		return parmNm;
	}
	public void setParmNm(String parmNm) {
		this.parmNm = parmNm;
	}
	public String getParmDc() {
		return parmDc;
	}
	public void setParmDc(String parmDc) {
		this.parmDc = parmDc;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}