package pe.dido.svr.lnkdesign.model;

import java.io.Serializable;

public class LnkIfPgmMeta implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lnk_if_pgm_meta
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm_meta.DATA_ATRB
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dataAtrb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm_meta.DATA_IEM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dataIem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm_meta.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String dc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm_meta.DATA_ATRB
	 * @return  the value of lnk_if_pgm_meta.DATA_ATRB
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDataAtrb() {
		return dataAtrb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm_meta.DATA_IEM
	 * @return  the value of lnk_if_pgm_meta.DATA_IEM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDataIem() {
		return dataIem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm_meta.DC
	 * @return  the value of lnk_if_pgm_meta.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getDc() {
		return dc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm_meta.DATA_ATRB
	 * @param dataAtrb  the value for lnk_if_pgm_meta.DATA_ATRB
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDataAtrb(String dataAtrb) {
		this.dataAtrb = dataAtrb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm_meta.DATA_IEM
	 * @param dataIem  the value for lnk_if_pgm_meta.DATA_IEM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDataIem(String dataIem) {
		this.dataIem = dataIem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm_meta.DC
	 * @param dc  the value for lnk_if_pgm_meta.DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setDc(String dc) {
		this.dc = dc;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_if_pgm_meta
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", dataIem=").append(dataIem);
		sb.append(", dataAtrb=").append(dataAtrb);
		sb.append(", dc=").append(dc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

}