package pe.dido.svr.lnkdesign.model;

import java.io.Serializable;

public class LnkIfIem implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lnk_if_iem
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_iem.ARVL_SYS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer arvlSysId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_iem.INTRFC_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String intrfcEnNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_iem.INTRFC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer intrfcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_iem.INTRFC_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String intrfcKrNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_iem.INTRFC_TCHNLGY_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String intrfcTchnlgyNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_iem.START_SYS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer startSysId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_if_iem
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		LnkIfIem other = (LnkIfIem) that;
		return (this.getIntrfcId() == null ? other.getIntrfcId() == null : this
				.getIntrfcId().equals(other.getIntrfcId()))
				&& (this.getIntrfcEnNm() == null ? other.getIntrfcEnNm() == null
						: this.getIntrfcEnNm().equals(other.getIntrfcEnNm()))
				&& (this.getIntrfcKrNm() == null ? other.getIntrfcKrNm() == null
						: this.getIntrfcKrNm().equals(other.getIntrfcKrNm()))
				&& (this.getIntrfcTchnlgyNm() == null ? other
						.getIntrfcTchnlgyNm() == null : this
						.getIntrfcTchnlgyNm()
						.equals(other.getIntrfcTchnlgyNm()))
				&& (this.getStartSysId() == null ? other.getStartSysId() == null
						: this.getStartSysId().equals(other.getStartSysId()))
				&& (this.getArvlSysId() == null ? other.getArvlSysId() == null
						: this.getArvlSysId().equals(other.getArvlSysId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_iem.ARVL_SYS_ID
	 * @return  the value of lnk_if_iem.ARVL_SYS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getArvlSysId() {
		return arvlSysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_iem.INTRFC_EN_NM
	 * @return  the value of lnk_if_iem.INTRFC_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getIntrfcEnNm() {
		return intrfcEnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_iem.INTRFC_ID
	 * @return  the value of lnk_if_iem.INTRFC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getIntrfcId() {
		return intrfcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_iem.INTRFC_KR_NM
	 * @return  the value of lnk_if_iem.INTRFC_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getIntrfcKrNm() {
		return intrfcKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_iem.INTRFC_TCHNLGY_NM
	 * @return  the value of lnk_if_iem.INTRFC_TCHNLGY_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getIntrfcTchnlgyNm() {
		return intrfcTchnlgyNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_iem.START_SYS_ID
	 * @return  the value of lnk_if_iem.START_SYS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getStartSysId() {
		return startSysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_if_iem
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getIntrfcId() == null) ? 0 : getIntrfcId().hashCode());
		result = prime * result
				+ ((getIntrfcEnNm() == null) ? 0 : getIntrfcEnNm().hashCode());
		result = prime * result
				+ ((getIntrfcKrNm() == null) ? 0 : getIntrfcKrNm().hashCode());
		result = prime
				* result
				+ ((getIntrfcTchnlgyNm() == null) ? 0 : getIntrfcTchnlgyNm()
						.hashCode());
		result = prime * result
				+ ((getStartSysId() == null) ? 0 : getStartSysId().hashCode());
		result = prime * result
				+ ((getArvlSysId() == null) ? 0 : getArvlSysId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_iem.ARVL_SYS_ID
	 * @param arvlSysId  the value for lnk_if_iem.ARVL_SYS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setArvlSysId(Integer arvlSysId) {
		this.arvlSysId = arvlSysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_iem.INTRFC_EN_NM
	 * @param intrfcEnNm  the value for lnk_if_iem.INTRFC_EN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIntrfcEnNm(String intrfcEnNm) {
		this.intrfcEnNm = intrfcEnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_iem.INTRFC_ID
	 * @param intrfcId  the value for lnk_if_iem.INTRFC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIntrfcId(Integer intrfcId) {
		this.intrfcId = intrfcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_iem.INTRFC_KR_NM
	 * @param intrfcKrNm  the value for lnk_if_iem.INTRFC_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIntrfcKrNm(String intrfcKrNm) {
		this.intrfcKrNm = intrfcKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_iem.INTRFC_TCHNLGY_NM
	 * @param intrfcTchnlgyNm  the value for lnk_if_iem.INTRFC_TCHNLGY_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIntrfcTchnlgyNm(String intrfcTchnlgyNm) {
		this.intrfcTchnlgyNm = intrfcTchnlgyNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_iem.START_SYS_ID
	 * @param startSysId  the value for lnk_if_iem.START_SYS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setStartSysId(Integer startSysId) {
		this.startSysId = startSysId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_if_iem
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", intrfcId=").append(intrfcId);
		sb.append(", intrfcEnNm=").append(intrfcEnNm);
		sb.append(", intrfcKrNm=").append(intrfcKrNm);
		sb.append(", intrfcTchnlgyNm=").append(intrfcTchnlgyNm);
		sb.append(", startSysId=").append(startSysId);
		sb.append(", arvlSysId=").append(arvlSysId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}