package pe.dido.svr.lnkdesign.model;

import java.io.Serializable;

public class LnkIfPgm implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lnk_if_pgm
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm.CYCLE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cycle;
	private int intrfcId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm.INTRLCK_IEM_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String intrlckIemNm;

	private int pgmId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm.PGM_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String pgmNm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm.RM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String rm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_if_pgm.SCRTY_GRAD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String scrtyGrad;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm.CYCLE
	 * @return  the value of lnk_if_pgm.CYCLE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCycle() {
		return cycle;
	}
	/**
	 * @return the intrfcId
	 */
	public int getIntrfcId() {
		return intrfcId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm.INTRLCK_IEM_NM
	 * @return  the value of lnk_if_pgm.INTRLCK_IEM_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getIntrlckIemNm() {
		return intrlckIemNm;
	}
	/**
	 * @return the pgmId
	 */
	public int getPgmId() {
		return pgmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm.PGM_NM
	 * @return  the value of lnk_if_pgm.PGM_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getPgmNm() {
		return pgmNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm.RM
	 * @return  the value of lnk_if_pgm.RM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getRm() {
		return rm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_if_pgm.SCRTY_GRAD
	 * @return  the value of lnk_if_pgm.SCRTY_GRAD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getScrtyGrad() {
		return scrtyGrad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm.CYCLE
	 * @param cycle  the value for lnk_if_pgm.CYCLE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	/**
	 * @param intrfcId the intrfcId to set
	 */
	public void setIntrfcId(int intrfcId) {
		this.intrfcId = intrfcId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm.INTRLCK_IEM_NM
	 * @param intrlckIemNm  the value for lnk_if_pgm.INTRLCK_IEM_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setIntrlckIemNm(String intrlckIemNm) {
		this.intrlckIemNm = intrlckIemNm;
	}

	/**
	 * @param pgmId the pgmId to set
	 */
	public void setPgmId(int pgmId) {
		this.pgmId = pgmId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm.PGM_NM
	 * @param pgmNm  the value for lnk_if_pgm.PGM_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPgmNm(String pgmNm) {
		this.pgmNm = pgmNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm.RM
	 * @param rm  the value for lnk_if_pgm.RM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setRm(String rm) {
		this.rm = rm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_if_pgm.SCRTY_GRAD
	 * @param scrtyGrad  the value for lnk_if_pgm.SCRTY_GRAD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScrtyGrad(String scrtyGrad) {
		this.scrtyGrad = scrtyGrad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_if_pgm
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pgmNm=").append(pgmNm);
		sb.append(", intrlckIemNm=").append(intrlckIemNm);
		sb.append(", cycle=").append(cycle);
		sb.append(", scrtyGrad=").append(scrtyGrad);
		sb.append(", rm=").append(rm);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}


}