package pe.dido.svr.lnkdesign.model;

import java.io.Serializable;

public class LnkIfIem implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lnk_if_iem
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	public Integer getIntrfcId() {
		return intrfcId;
	}
	public void setIntrfcId(Integer intrfcId) {
		this.intrfcId = intrfcId;
	}
	public String getIntrfcEnNm() {
		return intrfcEnNm;
	}
	public void setIntrfcEnNm(String intrfcEnNm) {
		this.intrfcEnNm = intrfcEnNm;
	}
	public String getIntrfcKrNm() {
		return intrfcKrNm;
	}
	public void setIntrfcKrNm(String intrfcKrNm) {
		this.intrfcKrNm = intrfcKrNm;
	}
	public String getIntrfcTchnlgyNm() {
		return intrfcTchnlgyNm;
	}
	public void setIntrfcTchnlgyNm(String intrfcTchnlgyNm) {
		this.intrfcTchnlgyNm = intrfcTchnlgyNm;
	}
	public String getIntrfcTchnlgyDc() {
		return intrfcTchnlgyDc;
	}
	public void setIntrfcTchnlgyDc(String intrfcTchnlgyDc) {
		this.intrfcTchnlgyDc = intrfcTchnlgyDc;
	}
	public String getIntrfcRstrctMatter() {
		return intrfcRstrctMatter;
	}
	public void setIntrfcRstrctMatter(String intrfcRstrctMatter) {
		this.intrfcRstrctMatter = intrfcRstrctMatter;
	}
	public String getIntrfcDc() {
		return intrfcDc;
	}
	public void setIntrfcDc(String intrfcDc) {
		this.intrfcDc = intrfcDc;
	}
	public Integer getStartSysId() {
		return startSysId;
	}
	public void setStartSysId(Integer startSysId) {
		this.startSysId = startSysId;
	}
	public Integer getArvlSysId() {
		return arvlSysId;
	}
	public void setArvlSysId(Integer arvlSysId) {
		this.arvlSysId = arvlSysId;
	}
	private Integer intrfcId;
	private String intrfcEnNm;
	private String intrfcKrNm;
	private String intrfcTchnlgyNm;
	private String intrfcTchnlgyDc;
	private String intrfcRstrctMatter;
	private String intrfcDc;
	private Integer startSysId;
	private Integer arvlSysId;
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}