package pe.dido.svr.lnkdesign.model;

import java.io.Serializable;

public class LnkSysNode implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table lnk_sys_node
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_sys_node.SYS_NODE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer sysNodeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lnk_sys_node.SYS_NODE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String sysNodeNm;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_sys_node
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		LnkSysNode other = (LnkSysNode) that;
		return (this.getSysNodeId() == null ? other.getSysNodeId() == null
				: this.getSysNodeId().equals(other.getSysNodeId()))
				&& (this.getSysNodeNm() == null ? other.getSysNodeNm() == null
						: this.getSysNodeNm().equals(other.getSysNodeNm()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_sys_node.SYS_NODE_ID
	 * @return  the value of lnk_sys_node.SYS_NODE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getSysNodeId() {
		return sysNodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lnk_sys_node.SYS_NODE_NM
	 * @return  the value of lnk_sys_node.SYS_NODE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getSysNodeNm() {
		return sysNodeNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_sys_node
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getSysNodeId() == null) ? 0 : getSysNodeId().hashCode());
		result = prime * result
				+ ((getSysNodeNm() == null) ? 0 : getSysNodeNm().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_sys_node.SYS_NODE_ID
	 * @param sysNodeId  the value for lnk_sys_node.SYS_NODE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setSysNodeId(Integer sysNodeId) {
		this.sysNodeId = sysNodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lnk_sys_node.SYS_NODE_NM
	 * @param sysNodeNm  the value for lnk_sys_node.SYS_NODE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setSysNodeNm(String sysNodeNm) {
		this.sysNodeNm = sysNodeNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lnk_sys_node
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", sysNodeId=").append(sysNodeId);
		sb.append(", sysNodeNm=").append(sysNodeNm);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}