package pe.dido.svr.testmngt.model;

import java.io.Serializable;
import java.util.Date;

public class TestResult implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test_result
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_result.MANAGT_DE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Date managtDe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_result.MANER
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String maner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_result.TEST_EXC_MAN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String testExcMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_result.TEST_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String testTy;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_result.MANAGT_DE
	 * @return  the value of test_result.MANAGT_DE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Date getManagtDe() {
		return managtDe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_result.MANER
	 * @return  the value of test_result.MANER
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getManer() {
		return maner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_result.TEST_EXC_MAN
	 * @return  the value of test_result.TEST_EXC_MAN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTestExcMan() {
		return testExcMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_result.TEST_TY
	 * @return  the value of test_result.TEST_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTestTy() {
		return testTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_result.MANAGT_DE
	 * @param managtDe  the value for test_result.MANAGT_DE
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setManagtDe(Date managtDe) {
		this.managtDe = managtDe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_result.MANER
	 * @param maner  the value for test_result.MANER
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setManer(String maner) {
		this.maner = maner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_result.TEST_EXC_MAN
	 * @param testExcMan  the value for test_result.TEST_EXC_MAN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTestExcMan(String testExcMan) {
		this.testExcMan = testExcMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_result.TEST_TY
	 * @param testTy  the value for test_result.TEST_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTestTy(String testTy) {
		this.testTy = testTy;
	}
}