package pe.dido.svr.testmngt.model;

import java.io.Serializable;

public class TestPln implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table test_pln
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_pln.TESTCASE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String testcaseNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_pln.TEST_IEM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String testIem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_pln.TEST_PLN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer testPlnId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column test_pln.TEST_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String testTy;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_pln
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		TestPln other = (TestPln) that;
		return (this.getTestPlnId() == null ? other.getTestPlnId() == null
				: this.getTestPlnId().equals(other.getTestPlnId()))
				&& (this.getTestTy() == null ? other.getTestTy() == null : this
						.getTestTy().equals(other.getTestTy()))
				&& (this.getTestIem() == null ? other.getTestIem() == null
						: this.getTestIem().equals(other.getTestIem()))
				&& (this.getTestcaseNm() == null ? other.getTestcaseNm() == null
						: this.getTestcaseNm().equals(other.getTestcaseNm()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_pln.TESTCASE_NM
	 * @return  the value of test_pln.TESTCASE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTestcaseNm() {
		return testcaseNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_pln.TEST_IEM
	 * @return  the value of test_pln.TEST_IEM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTestIem() {
		return testIem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_pln.TEST_PLN_ID
	 * @return  the value of test_pln.TEST_PLN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getTestPlnId() {
		return testPlnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column test_pln.TEST_TY
	 * @return  the value of test_pln.TEST_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTestTy() {
		return testTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_pln
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getTestPlnId() == null) ? 0 : getTestPlnId().hashCode());
		result = prime * result
				+ ((getTestTy() == null) ? 0 : getTestTy().hashCode());
		result = prime * result
				+ ((getTestIem() == null) ? 0 : getTestIem().hashCode());
		result = prime * result
				+ ((getTestcaseNm() == null) ? 0 : getTestcaseNm().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_pln.TESTCASE_NM
	 * @param testcaseNm  the value for test_pln.TESTCASE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTestcaseNm(String testcaseNm) {
		this.testcaseNm = testcaseNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_pln.TEST_IEM
	 * @param testIem  the value for test_pln.TEST_IEM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTestIem(String testIem) {
		this.testIem = testIem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_pln.TEST_PLN_ID
	 * @param testPlnId  the value for test_pln.TEST_PLN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTestPlnId(Integer testPlnId) {
		this.testPlnId = testPlnId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column test_pln.TEST_TY
	 * @param testTy  the value for test_pln.TEST_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTestTy(String testTy) {
		this.testTy = testTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table test_pln
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", testPlnId=").append(testPlnId);
		sb.append(", testTy=").append(testTy);
		sb.append(", testIem=").append(testIem);
		sb.append(", testcaseNm=").append(testcaseNm);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}