package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizActor implements Serializable {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_actor.BIZ_ACTOR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bizActorDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_actor.BIZ_ACTOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer bizActorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_actor.BIZ_ACTOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bizActorNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_actor.CNDCY_ACTOR_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cndcyActorYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_actor.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer pckageId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BizActor other = (BizActor) that;
		return (this.getBizActorId() == null ? other.getBizActorId() == null
				: this.getBizActorId().equals(other.getBizActorId()))
				&& (this.getBizActorNm() == null ? other.getBizActorNm() == null
						: this.getBizActorNm().equals(other.getBizActorNm()))
				&& (this.getCndcyActorYn() == null ? other.getCndcyActorYn() == null
						: this.getCndcyActorYn()
								.equals(other.getCndcyActorYn()))
				&& (this.getPckageId() == null ? other.getPckageId() == null
						: this.getPckageId().equals(other.getPckageId()))
				&& (this.getBizActorDc() == null ? other.getBizActorDc() == null
						: this.getBizActorDc().equals(other.getBizActorDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_actor.BIZ_ACTOR_DC
	 * @return  the value of biz_actor.BIZ_ACTOR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBizActorDc() {
		return bizActorDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_actor.BIZ_ACTOR_ID
	 * @return  the value of biz_actor.BIZ_ACTOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getBizActorId() {
		return bizActorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_actor.BIZ_ACTOR_NM
	 * @return  the value of biz_actor.BIZ_ACTOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBizActorNm() {
		return bizActorNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_actor.CNDCY_ACTOR_YN
	 * @return  the value of biz_actor.CNDCY_ACTOR_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCndcyActorYn() {
		return cndcyActorYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_actor.PCKAGE_ID
	 * @return  the value of biz_actor.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getPckageId() {
		return pckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getBizActorId() == null) ? 0 : getBizActorId().hashCode());
		result = prime * result
				+ ((getBizActorNm() == null) ? 0 : getBizActorNm().hashCode());
		result = prime
				* result
				+ ((getCndcyActorYn() == null) ? 0 : getCndcyActorYn()
						.hashCode());
		result = prime * result
				+ ((getPckageId() == null) ? 0 : getPckageId().hashCode());
		result = prime * result
				+ ((getBizActorDc() == null) ? 0 : getBizActorDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_actor.BIZ_ACTOR_DC
	 * @param bizActorDc  the value for biz_actor.BIZ_ACTOR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBizActorDc(String bizActorDc) {
		this.bizActorDc = bizActorDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_actor.BIZ_ACTOR_ID
	 * @param bizActorId  the value for biz_actor.BIZ_ACTOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBizActorId(Integer bizActorId) {
		this.bizActorId = bizActorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_actor.BIZ_ACTOR_NM
	 * @param bizActorNm  the value for biz_actor.BIZ_ACTOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBizActorNm(String bizActorNm) {
		this.bizActorNm = bizActorNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_actor.CNDCY_ACTOR_YN
	 * @param cndcyActorYn  the value for biz_actor.CNDCY_ACTOR_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCndcyActorYn(String cndcyActorYn) {
		this.cndcyActorYn = cndcyActorYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_actor.PCKAGE_ID
	 * @param pckageId  the value for biz_actor.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageId(Integer pckageId) {
		this.pckageId = pckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", bizActorId=").append(bizActorId);
		sb.append(", bizActorNm=").append(bizActorNm);
		sb.append(", cndcyActorYn=").append(cndcyActorYn);
		sb.append(", pckageId=").append(pckageId);
		sb.append(", bizActorDc=").append(bizActorDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}