package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizActor implements Serializable {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;

	private Integer bizActorId;
	private String bizActorNm;
	private String bizActorDc;
	private String cndcyActorYn;
	private Integer pckageId;
	public Integer getBizActorId() {
		return bizActorId;
	}
	public void setBizActorId(Integer bizActorId) {
		this.bizActorId = bizActorId;
	}
	public String getBizActorNm() {
		return bizActorNm;
	}
	public void setBizActorNm(String bizActorNm) {
		this.bizActorNm = bizActorNm;
	}
	public String getBizActorDc() {
		return bizActorDc;
	}
	public void setBizActorDc(String bizActorDc) {
		this.bizActorDc = bizActorDc;
	}
	public String getCndcyActorYn() {
		return cndcyActorYn;
	}
	public void setCndcyActorYn(String cndcyActorYn) {
		this.cndcyActorYn = cndcyActorYn;
	}
	public Integer getPckageId() {
		return pckageId;
	}
	public void setPckageId(Integer pckageId) {
		this.pckageId = pckageId;
	}

}