package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizCncpt implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_cncpt
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_cncpt.CNCPT_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cncptDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_cncpt.CNCPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer cncptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_cncpt.CNCPT_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cncptKrNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_cncpt.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer pckageId;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_cncpt
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BizCncpt other = (BizCncpt) that;
		return (this.getCncptId() == null ? other.getCncptId() == null : this
				.getCncptId().equals(other.getCncptId()))
				&& (this.getCncptKrNm() == null ? other.getCncptKrNm() == null
						: this.getCncptKrNm().equals(other.getCncptKrNm()))
				&& (this.getPckageId() == null ? other.getPckageId() == null
						: this.getPckageId().equals(other.getPckageId()))
				&& (this.getCncptDc() == null ? other.getCncptDc() == null
						: this.getCncptDc().equals(other.getCncptDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_cncpt.CNCPT_DC
	 * @return  the value of biz_cncpt.CNCPT_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCncptDc() {
		return cncptDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_cncpt.CNCPT_ID
	 * @return  the value of biz_cncpt.CNCPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getCncptId() {
		return cncptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_cncpt.CNCPT_KR_NM
	 * @return  the value of biz_cncpt.CNCPT_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCncptKrNm() {
		return cncptKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_cncpt.PCKAGE_ID
	 * @return  the value of biz_cncpt.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getPckageId() {
		return pckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_cncpt
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getCncptId() == null) ? 0 : getCncptId().hashCode());
		result = prime * result
				+ ((getCncptKrNm() == null) ? 0 : getCncptKrNm().hashCode());
		result = prime * result
				+ ((getPckageId() == null) ? 0 : getPckageId().hashCode());
		result = prime * result
				+ ((getCncptDc() == null) ? 0 : getCncptDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_cncpt.CNCPT_DC
	 * @param cncptDc  the value for biz_cncpt.CNCPT_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCncptDc(String cncptDc) {
		this.cncptDc = cncptDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_cncpt.CNCPT_ID
	 * @param cncptId  the value for biz_cncpt.CNCPT_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCncptId(Integer cncptId) {
		this.cncptId = cncptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_cncpt.CNCPT_KR_NM
	 * @param cncptKrNm  the value for biz_cncpt.CNCPT_KR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCncptKrNm(String cncptKrNm) {
		this.cncptKrNm = cncptKrNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_cncpt.PCKAGE_ID
	 * @param pckageId  the value for biz_cncpt.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageId(Integer pckageId) {
		this.pckageId = pckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_cncpt
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", cncptId=").append(cncptId);
		sb.append(", cncptKrNm=").append(cncptKrNm);
		sb.append(", pckageId=").append(pckageId);
		sb.append(", cncptDc=").append(cncptDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}