package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizProcs implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_procs
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_procs.CNDCY_UC_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cndcyUcYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_procs.PROCS_CD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String procsCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_procs.PROCS_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String procsDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_procs.PROCS_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String procsNm;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_procs.CNDCY_UC_YN
	 * @return  the value of biz_procs.CNDCY_UC_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCndcyUcYn() {
		return cndcyUcYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_procs.PROCS_CD
	 * @return  the value of biz_procs.PROCS_CD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getProcsCd() {
		return procsCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_procs.PROCS_DC
	 * @return  the value of biz_procs.PROCS_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getProcsDc() {
		return procsDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_procs.PROCS_NM
	 * @return  the value of biz_procs.PROCS_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getProcsNm() {
		return procsNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_procs.CNDCY_UC_YN
	 * @param cndcyUcYn  the value for biz_procs.CNDCY_UC_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCndcyUcYn(String cndcyUcYn) {
		this.cndcyUcYn = cndcyUcYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_procs.PROCS_CD
	 * @param procsCd  the value for biz_procs.PROCS_CD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setProcsCd(String procsCd) {
		this.procsCd = procsCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_procs.PROCS_DC
	 * @param procsDc  the value for biz_procs.PROCS_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setProcsDc(String procsDc) {
		this.procsDc = procsDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_procs.PROCS_NM
	 * @param procsNm  the value for biz_procs.PROCS_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setProcsNm(String procsNm) {
		this.procsNm = procsNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_procs
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", procsNm=").append(procsNm);
		sb.append(", procsCd=").append(procsCd);
		sb.append(", cndcyUcYn=").append(cndcyUcYn);
		sb.append(", procsDc=").append(procsDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

}