package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizPkg implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_pkg
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_pkg.MOTHER_PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer motherPckageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_pkg.PCKAGE_CD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String pckageCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_pkg.PCKAGE_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String pckageDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_pkg.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer pckageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_pkg.PCKAGE_LVL
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String pckageLvl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_pkg.PCKAGE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String pckageNm;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_pkg
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		BizPkg other = (BizPkg) that;
		return (this.getPckageId() == null ? other.getPckageId() == null : this
				.getPckageId().equals(other.getPckageId()))
				&& (this.getMotherPckageId() == null ? other
						.getMotherPckageId() == null : this.getMotherPckageId()
						.equals(other.getMotherPckageId()))
				&& (this.getPckageNm() == null ? other.getPckageNm() == null
						: this.getPckageNm().equals(other.getPckageNm()))
				&& (this.getPckageCd() == null ? other.getPckageCd() == null
						: this.getPckageCd().equals(other.getPckageCd()))
				&& (this.getPckageLvl() == null ? other.getPckageLvl() == null
						: this.getPckageLvl().equals(other.getPckageLvl()))
				&& (this.getPckageDc() == null ? other.getPckageDc() == null
						: this.getPckageDc().equals(other.getPckageDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_pkg.MOTHER_PCKAGE_ID
	 * @return  the value of biz_pkg.MOTHER_PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getMotherPckageId() {
		return motherPckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_pkg.PCKAGE_CD
	 * @return  the value of biz_pkg.PCKAGE_CD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getPckageCd() {
		return pckageCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_pkg.PCKAGE_DC
	 * @return  the value of biz_pkg.PCKAGE_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getPckageDc() {
		return pckageDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_pkg.PCKAGE_ID
	 * @return  the value of biz_pkg.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getPckageId() {
		return pckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_pkg.PCKAGE_LVL
	 * @return  the value of biz_pkg.PCKAGE_LVL
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getPckageLvl() {
		return pckageLvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_pkg.PCKAGE_NM
	 * @return  the value of biz_pkg.PCKAGE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getPckageNm() {
		return pckageNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_pkg
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getPckageId() == null) ? 0 : getPckageId().hashCode());
		result = prime
				* result
				+ ((getMotherPckageId() == null) ? 0 : getMotherPckageId()
						.hashCode());
		result = prime * result
				+ ((getPckageNm() == null) ? 0 : getPckageNm().hashCode());
		result = prime * result
				+ ((getPckageCd() == null) ? 0 : getPckageCd().hashCode());
		result = prime * result
				+ ((getPckageLvl() == null) ? 0 : getPckageLvl().hashCode());
		result = prime * result
				+ ((getPckageDc() == null) ? 0 : getPckageDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_pkg.MOTHER_PCKAGE_ID
	 * @param motherPckageId  the value for biz_pkg.MOTHER_PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setMotherPckageId(Integer motherPckageId) {
		this.motherPckageId = motherPckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_pkg.PCKAGE_CD
	 * @param pckageCd  the value for biz_pkg.PCKAGE_CD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageCd(String pckageCd) {
		this.pckageCd = pckageCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_pkg.PCKAGE_DC
	 * @param pckageDc  the value for biz_pkg.PCKAGE_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageDc(String pckageDc) {
		this.pckageDc = pckageDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_pkg.PCKAGE_ID
	 * @param pckageId  the value for biz_pkg.PCKAGE_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageId(Integer pckageId) {
		this.pckageId = pckageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_pkg.PCKAGE_LVL
	 * @param pckageLvl  the value for biz_pkg.PCKAGE_LVL
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageLvl(String pckageLvl) {
		this.pckageLvl = pckageLvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_pkg.PCKAGE_NM
	 * @param pckageNm  the value for biz_pkg.PCKAGE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setPckageNm(String pckageNm) {
		this.pckageNm = pckageNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_pkg
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pckageId=").append(pckageId);
		sb.append(", motherPckageId=").append(motherPckageId);
		sb.append(", pckageNm=").append(pckageNm);
		sb.append(", pckageCd=").append(pckageCd);
		sb.append(", pckageLvl=").append(pckageLvl);
		sb.append(", pckageDc=").append(pckageDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}