package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizPkg implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_pkg
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer pckageId;
	private Integer motherPckageId;
	private String pckageNm;
	private String pckageCd;
	private String pckageLvl;
	private String pckageDc;
	public Integer getPckageId() {
		return pckageId;
	}
	public void setPckageId(Integer pckageId) {
		this.pckageId = pckageId;
	}
	public Integer getMotherPckageId() {
		return motherPckageId;
	}
	public void setMotherPckageId(Integer motherPckageId) {
		this.motherPckageId = motherPckageId;
	}
	public String getPckageNm() {
		return pckageNm;
	}
	public void setPckageNm(String pckageNm) {
		this.pckageNm = pckageNm;
	}
	public String getPckageCd() {
		return pckageCd;
	}
	public void setPckageCd(String pckageCd) {
		this.pckageCd = pckageCd;
	}
	public String getPckageLvl() {
		return pckageLvl;
	}
	public void setPckageLvl(String pckageLvl) {
		this.pckageLvl = pckageLvl;
	}
	public String getPckageDc() {
		return pckageDc;
	}
	public void setPckageDc(String pckageDc) {
		this.pckageDc = pckageDc;
	}
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}