package pe.dido.svr.bizmodeling.model;

import java.io.Serializable;

public class BizRule implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_rule
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_rule.BIZ_ACTN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bizActnNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_rule.BIZ_RULE_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bizRuleDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_rule.BIZ_RULE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String bizRuleNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_rule.CNDCY_EVENT_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cndcyEventYn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_rule.BIZ_ACTN_NM
	 * @return  the value of biz_rule.BIZ_ACTN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBizActnNm() {
		return bizActnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_rule.BIZ_RULE_DC
	 * @return  the value of biz_rule.BIZ_RULE_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBizRuleDc() {
		return bizRuleDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_rule.BIZ_RULE_NM
	 * @return  the value of biz_rule.BIZ_RULE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getBizRuleNm() {
		return bizRuleNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_rule.CNDCY_EVENT_YN
	 * @return  the value of biz_rule.CNDCY_EVENT_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCndcyEventYn() {
		return cndcyEventYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_rule.BIZ_ACTN_NM
	 * @param bizActnNm  the value for biz_rule.BIZ_ACTN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBizActnNm(String bizActnNm) {
		this.bizActnNm = bizActnNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_rule.BIZ_RULE_DC
	 * @param bizRuleDc  the value for biz_rule.BIZ_RULE_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBizRuleDc(String bizRuleDc) {
		this.bizRuleDc = bizRuleDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_rule.BIZ_RULE_NM
	 * @param bizRuleNm  the value for biz_rule.BIZ_RULE_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setBizRuleNm(String bizRuleNm) {
		this.bizRuleNm = bizRuleNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_rule.CNDCY_EVENT_YN
	 * @param cndcyEventYn  the value for biz_rule.CNDCY_EVENT_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCndcyEventYn(String cndcyEventYn) {
		this.cndcyEventYn = cndcyEventYn;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_rule
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", bizActnNm=").append(bizActnNm);
		sb.append(", bizRuleNm=").append(bizRuleNm);
		sb.append(", cndcyEventYn=").append(cndcyEventYn);
		sb.append(", bizRuleDc=").append(bizRuleDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	
}