package pe.dido.svr.ucsmodeling.model;

import java.io.Serializable;

public class UcActor implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_actor.ACTOR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String actorDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_actor.ACTOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer actorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_actor.ACTOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String actorNm;
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UcActor other = (UcActor) that;
		return (this.getActorId() == null ? other.getActorId() == null : this
				.getActorId().equals(other.getActorId()))
				&& (this.getActorNm() == null ? other.getActorNm() == null
						: this.getActorNm().equals(other.getActorNm()))
				&& (this.getActorDc() == null ? other.getActorDc() == null
						: this.getActorDc().equals(other.getActorDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_actor.ACTOR_DC
	 * @return  the value of uc_actor.ACTOR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getActorDc() {
		return actorDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_actor.ACTOR_ID
	 * @return  the value of uc_actor.ACTOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getActorId() {
		return actorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_actor.ACTOR_NM
	 * @return  the value of uc_actor.ACTOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getActorNm() {
		return actorNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getActorId() == null) ? 0 : getActorId().hashCode());
		result = prime * result
				+ ((getActorNm() == null) ? 0 : getActorNm().hashCode());
		result = prime * result
				+ ((getActorDc() == null) ? 0 : getActorDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_actor.ACTOR_DC
	 * @param actorDc  the value for uc_actor.ACTOR_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setActorDc(String actorDc) {
		this.actorDc = actorDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_actor.ACTOR_ID
	 * @param actorId  the value for uc_actor.ACTOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setActorId(Integer actorId) {
		this.actorId = actorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_actor.ACTOR_NM
	 * @param actorNm  the value for uc_actor.ACTOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setActorNm(String actorNm) {
		this.actorNm = actorNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_actor
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", actorId=").append(actorId);
		sb.append(", actorNm=").append(actorNm);
		sb.append(", actorDc=").append(actorDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}