package pe.dido.svr.ucsmodeling.model;

import java.io.Serializable;

public class UcEventFlow implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_event_flow
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer eventId;
	private Integer ucId;
	private String eventNm;
	private String flowTy;
	private String dicaryCnd;
	private String flowDc;
	private String aftfatCnd;
	private String rtrnLc;
	public Integer getEventId() {
		return eventId;
	}
	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}
	public Integer getUcId() {
		return ucId;
	}
	public void setUcId(Integer ucId) {
		this.ucId = ucId;
	}
	public String getEventNm() {
		return eventNm;
	}
	public void setEventNm(String eventNm) {
		this.eventNm = eventNm;
	}
	public String getFlowTy() {
		return flowTy;
	}
	public void setFlowTy(String flowTy) {
		this.flowTy = flowTy;
	}
	public String getDicaryCnd() {
		return dicaryCnd;
	}
	public void setDicaryCnd(String dicaryCnd) {
		this.dicaryCnd = dicaryCnd;
	}
	public String getFlowDc() {
		return flowDc;
	}
	public void setFlowDc(String flowDc) {
		this.flowDc = flowDc;
	}
	public String getAftfatCnd() {
		return aftfatCnd;
	}
	public void setAftfatCnd(String aftfatCnd) {
		this.aftfatCnd = aftfatCnd;
	}
	public String getRtrnLc() {
		return rtrnLc;
	}
	public void setRtrnLc(String rtrnLc) {
		this.rtrnLc = rtrnLc;
	}
	private String crudTy;
	public String getCrudTy() {
		return crudTy;
	}
	public void setCrudTy(String crudTy) {
		this.crudTy = crudTy;
	}
}