package pe.dido.svr.ucsmodeling.model;

import java.io.Serializable;

public class UcEventFlow implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_event_flow
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_event_flow.EVENT_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String eventNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_event_flow.FLOW_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String flowTy;
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_event_flow.EVENT_NM
	 * @return  the value of uc_event_flow.EVENT_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getEventNm() {
		return eventNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_event_flow.FLOW_TY
	 * @return  the value of uc_event_flow.FLOW_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getFlowTy() {
		return flowTy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_event_flow.EVENT_NM
	 * @param eventNm  the value for uc_event_flow.EVENT_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setEventNm(String eventNm) {
		this.eventNm = eventNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_event_flow.FLOW_TY
	 * @param flowTy  the value for uc_event_flow.FLOW_TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setFlowTy(String flowTy) {
		this.flowTy = flowTy;
	}
}