package pe.dido.svr.ucsmodeling.model;

import java.io.Serializable;

public class UcM implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_m.CMMN_UC_AT
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String cmmnUcAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_m.PROCS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer procsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_m.REFRN_UC_AT
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String refrnUcAt;
	private Integer ucId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_m.UC_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String ucIdntfr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column uc_m.UC_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String ucNm;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UcM other = (UcM) that;
		return (this.getUcId() == null ? other.getUcId() == null : this
				.getUcId().equals(other.getUcId()))
				&& (this.getUcIdntfr() == null ? other.getUcIdntfr() == null
						: this.getUcIdntfr().equals(other.getUcIdntfr()))
				&& (this.getUcNm() == null ? other.getUcNm() == null : this
						.getUcNm().equals(other.getUcNm()))
				&& (this.getRefrnUcAt() == null ? other.getRefrnUcAt() == null
						: this.getRefrnUcAt().equals(other.getRefrnUcAt()))
				&& (this.getCmmnUcAt() == null ? other.getCmmnUcAt() == null
						: this.getCmmnUcAt().equals(other.getCmmnUcAt()))
				&& (this.getProcsId() == null ? other.getProcsId() == null
						: this.getProcsId().equals(other.getProcsId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_m.CMMN_UC_AT
	 * @return  the value of uc_m.CMMN_UC_AT
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getCmmnUcAt() {
		return cmmnUcAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_m.PROCS_ID
	 * @return  the value of uc_m.PROCS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getProcsId() {
		return procsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_m.REFRN_UC_AT
	 * @return  the value of uc_m.REFRN_UC_AT
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getRefrnUcAt() {
		return refrnUcAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_m.UC_ID
	 * @return  the value of uc_m.UC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getUcId() {
		return ucId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_m.UC_IDNTFR
	 * @return  the value of uc_m.UC_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getUcIdntfr() {
		return ucIdntfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column uc_m.UC_NM
	 * @return  the value of uc_m.UC_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getUcNm() {
		return ucNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getUcId() == null) ? 0 : getUcId().hashCode());
		result = prime * result
				+ ((getUcIdntfr() == null) ? 0 : getUcIdntfr().hashCode());
		result = prime * result
				+ ((getUcNm() == null) ? 0 : getUcNm().hashCode());
		result = prime * result
				+ ((getRefrnUcAt() == null) ? 0 : getRefrnUcAt().hashCode());
		result = prime * result
				+ ((getCmmnUcAt() == null) ? 0 : getCmmnUcAt().hashCode());
		result = prime * result
				+ ((getProcsId() == null) ? 0 : getProcsId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_m.CMMN_UC_AT
	 * @param cmmnUcAt  the value for uc_m.CMMN_UC_AT
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setCmmnUcAt(String cmmnUcAt) {
		this.cmmnUcAt = cmmnUcAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_m.PROCS_ID
	 * @param procsId  the value for uc_m.PROCS_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setProcsId(Integer procsId) {
		this.procsId = procsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_m.REFRN_UC_AT
	 * @param refrnUcAt  the value for uc_m.REFRN_UC_AT
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setRefrnUcAt(String refrnUcAt) {
		this.refrnUcAt = refrnUcAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_m.UC_ID
	 * @param ucId  the value for uc_m.UC_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setUcId(Integer ucId) {
		this.ucId = ucId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_m.UC_IDNTFR
	 * @param ucIdntfr  the value for uc_m.UC_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setUcIdntfr(String ucIdntfr) {
		this.ucIdntfr = ucIdntfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column uc_m.UC_NM
	 * @param ucNm  the value for uc_m.UC_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setUcNm(String ucNm) {
		this.ucNm = ucNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table uc_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", ucId=").append(ucId);
		sb.append(", ucIdntfr=").append(ucIdntfr);
		sb.append(", ucNm=").append(ucNm);
		sb.append(", refrnUcAt=").append(refrnUcAt);
		sb.append(", cmmnUcAt=").append(cmmnUcAt);
		sb.append(", procsId=").append(procsId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}