package pe.dido.svr.ucsmodeling.model;

import java.io.Serializable;

public class UcM implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table uc_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer ucId;
	private String ucIdntfr;
	private String ucNm;
	private String sumry;
	private String chnge;
	private String adiMatter;
	private String senario_dc;
	private String refrnUcAt;
	private String cmmnUcAt;
	private Integer procsId;
	public Integer getUcId() {
		return ucId;
	}
	public void setUcId(Integer ucId) {
		this.ucId = ucId;
	}
	public String getUcIdntfr() {
		return ucIdntfr;
	}
	public void setUcIdntfr(String ucIdntfr) {
		this.ucIdntfr = ucIdntfr;
	}
	public String getUcNm() {
		return ucNm;
	}
	public void setUcNm(String ucNm) {
		this.ucNm = ucNm;
	}
	public String getSumry() {
		return sumry;
	}
	public void setSumry(String sumry) {
		this.sumry = sumry;
	}
	public String getChnge() {
		return chnge;
	}
	public void setChnge(String chnge) {
		this.chnge = chnge;
	}
	public String getAdiMatter() {
		return adiMatter;
	}
	public void setAdiMatter(String adiMatter) {
		this.adiMatter = adiMatter;
	}
	public String getSenario_dc() {
		return senario_dc;
	}
	public void setSenario_dc(String senario_dc) {
		this.senario_dc = senario_dc;
	}
	public String getRefrnUcAt() {
		return refrnUcAt;
	}
	public void setRefrnUcAt(String refrnUcAt) {
		this.refrnUcAt = refrnUcAt;
	}
	public String getCmmnUcAt() {
		return cmmnUcAt;
	}
	public void setCmmnUcAt(String cmmnUcAt) {
		this.cmmnUcAt = cmmnUcAt;
	}
	public Integer getProcsId() {
		return procsId;
	}
	public void setProcsId(Integer procsId) {
		this.procsId = procsId;
	}

	
	private String statusYn;
	public String getStatusYn() {
		return statusYn;
	}
	public void setStatusYn(String statusYn) {
		this.statusYn = statusYn;
	}	
	
}