package pe.dido.svr.uidesign.model;

import java.io.Serializable;

public class UiAuthorMap implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ui_author_map
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_author_map.AUTHOR_APPLC_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String authorApplcYn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_author_map.AUTHOR_APPLC_YN
	 * @return  the value of ui_author_map.AUTHOR_APPLC_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getAuthorApplcYn() {
		return authorApplcYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_author_map.AUTHOR_APPLC_YN
	 * @param authorApplcYn  the value for ui_author_map.AUTHOR_APPLC_YN
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setAuthorApplcYn(String authorApplcYn) {
		this.authorApplcYn = authorApplcYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_author_map
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", authorApplcYn=").append(authorApplcYn);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

}