package pe.dido.svr.uidesign.model;

import java.io.Serializable;

public class UiAuthor implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ui_author
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_author.AUTHOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_author.AUTHOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String authorNm;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_author
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UiAuthor other = (UiAuthor) that;
		return (this.getAuthorId() == null ? other.getAuthorId() == null : this
				.getAuthorId().equals(other.getAuthorId()))
				&& (this.getAuthorNm() == null ? other.getAuthorNm() == null
						: this.getAuthorNm().equals(other.getAuthorNm()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_author.AUTHOR_ID
	 * @return  the value of ui_author.AUTHOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_author.AUTHOR_NM
	 * @return  the value of ui_author.AUTHOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getAuthorNm() {
		return authorNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_author
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getAuthorId() == null) ? 0 : getAuthorId().hashCode());
		result = prime * result
				+ ((getAuthorNm() == null) ? 0 : getAuthorNm().hashCode());
		return result;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_author.AUTHOR_ID
	 * @param authorId  the value for ui_author.AUTHOR_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_author.AUTHOR_NM
	 * @param authorNm  the value for ui_author.AUTHOR_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setAuthorNm(String authorNm) {
		this.authorNm = authorNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_author
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", authorId=").append(authorId);
		sb.append(", authorNm=").append(authorNm);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}