package pe.dido.svr.uidesign.model;

import java.io.Serializable;

public class UiAuthor implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ui_author
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer authorId;
	private String authorNm;
	public Integer getAuthorId() {
		return authorId;
	}
	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}
	public String getAuthorNm() {
		return authorNm;
	}
	public void setAuthorNm(String authorNm) {
		this.authorNm = authorNm;
	}

}