package pe.dido.svr.uidesign.model;

import java.io.Serializable;

public class UiM implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ui_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.MENU_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.SCRIN_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String scrinDc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.SCRIN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private Integer scrinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.SCRIN_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String scrinIdntfr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.SCRIN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String scrinNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.SCRTY_GRAD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String scrtyGrad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ui_m.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private String ty;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		UiM other = (UiM) that;
		return (this.getScrinId() == null ? other.getScrinId() == null : this
				.getScrinId().equals(other.getScrinId()))
				&& (this.getScrinIdntfr() == null ? other.getScrinIdntfr() == null
						: this.getScrinIdntfr().equals(other.getScrinIdntfr()))
				&& (this.getScrinNm() == null ? other.getScrinNm() == null
						: this.getScrinNm().equals(other.getScrinNm()))
				&& (this.getScrtyGrad() == null ? other.getScrtyGrad() == null
						: this.getScrtyGrad().equals(other.getScrtyGrad()))
				&& (this.getTy() == null ? other.getTy() == null : this.getTy()
						.equals(other.getTy()))
				&& (this.getMenuId() == null ? other.getMenuId() == null : this
						.getMenuId().equals(other.getMenuId()))
				&& (this.getScrinDc() == null ? other.getScrinDc() == null
						: this.getScrinDc().equals(other.getScrinDc()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.MENU_ID
	 * @return  the value of ui_m.MENU_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.SCRIN_DC
	 * @return  the value of ui_m.SCRIN_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getScrinDc() {
		return scrinDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.SCRIN_ID
	 * @return  the value of ui_m.SCRIN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public Integer getScrinId() {
		return scrinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.SCRIN_IDNTFR
	 * @return  the value of ui_m.SCRIN_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getScrinIdntfr() {
		return scrinIdntfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.SCRIN_NM
	 * @return  the value of ui_m.SCRIN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getScrinNm() {
		return scrinNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.SCRTY_GRAD
	 * @return  the value of ui_m.SCRTY_GRAD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getScrtyGrad() {
		return scrtyGrad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ui_m.TY
	 * @return  the value of ui_m.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public String getTy() {
		return ty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((getScrinId() == null) ? 0 : getScrinId().hashCode());
		result = prime
				* result
				+ ((getScrinIdntfr() == null) ? 0 : getScrinIdntfr().hashCode());
		result = prime * result
				+ ((getScrinNm() == null) ? 0 : getScrinNm().hashCode());
		result = prime * result
				+ ((getScrtyGrad() == null) ? 0 : getScrtyGrad().hashCode());
		result = prime * result + ((getTy() == null) ? 0 : getTy().hashCode());
		result = prime * result
				+ ((getMenuId() == null) ? 0 : getMenuId().hashCode());
		result = prime * result
				+ ((getScrinDc() == null) ? 0 : getScrinDc().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.MENU_ID
	 * @param menuId  the value for ui_m.MENU_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.SCRIN_DC
	 * @param scrinDc  the value for ui_m.SCRIN_DC
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScrinDc(String scrinDc) {
		this.scrinDc = scrinDc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.SCRIN_ID
	 * @param scrinId  the value for ui_m.SCRIN_ID
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScrinId(Integer scrinId) {
		this.scrinId = scrinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.SCRIN_IDNTFR
	 * @param scrinIdntfr  the value for ui_m.SCRIN_IDNTFR
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScrinIdntfr(String scrinIdntfr) {
		this.scrinIdntfr = scrinIdntfr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.SCRIN_NM
	 * @param scrinNm  the value for ui_m.SCRIN_NM
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScrinNm(String scrinNm) {
		this.scrinNm = scrinNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.SCRTY_GRAD
	 * @param scrtyGrad  the value for ui_m.SCRTY_GRAD
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setScrtyGrad(String scrtyGrad) {
		this.scrtyGrad = scrtyGrad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ui_m.TY
	 * @param ty  the value for ui_m.TY
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	public void setTy(String ty) {
		this.ty = ty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ui_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", scrinId=").append(scrinId);
		sb.append(", scrinIdntfr=").append(scrinIdntfr);
		sb.append(", scrinNm=").append(scrinNm);
		sb.append(", scrtyGrad=").append(scrtyGrad);
		sb.append(", ty=").append(ty);
		sb.append(", menuId=").append(menuId);
		sb.append(", scrinDc=").append(scrinDc);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}