package pe.dido.svr.uidesign.model;

import java.io.Serializable;

public class UiM implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ui_m
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Integer scrinId;
	private String scrinIdntfr;
	private String scrinNm;
	private String scrinDc;
	private String scrtyGrad;
	private String ty;
	private Integer menuId;
	public Integer getScrinId() {
		return scrinId;
	}
	public void setScrinId(Integer scrinId) {
		this.scrinId = scrinId;
	}
	public String getScrinIdntfr() {
		return scrinIdntfr;
	}
	public void setScrinIdntfr(String scrinIdntfr) {
		this.scrinIdntfr = scrinIdntfr;
	}
	public String getScrinNm() {
		return scrinNm;
	}
	public void setScrinNm(String scrinNm) {
		this.scrinNm = scrinNm;
	}
	public String getScrinDc() {
		return scrinDc;
	}
	public void setScrinDc(String scrinDc) {
		this.scrinDc = scrinDc;
	}
	public String getScrtyGrad() {
		return scrtyGrad;
	}
	public void setScrtyGrad(String scrtyGrad) {
		this.scrtyGrad = scrtyGrad;
	}
	public String getTy() {
		return ty;
	}
	public void setTy(String ty) {
		this.ty = ty;
	}
	public Integer getMenuId() {
		return menuId;
	}
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	
	private String statusYn;
	public String getStatusYn() {
		return statusYn;
	}
	public void setStatusYn(String statusYn) {
		this.statusYn = statusYn;
	}		
}