package pe.dido.svr.uidesign.model;

import java.io.Serializable;

public class UiMenuPkg implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ui_menu_pkg
	 * @mbggenerated  Mon Aug 25 18:12:32 KST 2014
	 */
	private static final long serialVersionUID = 1L;
	
	
	
	private Integer menuId;
	private Integer motherMenuId;
	private String menuNm;
	private String menuCode;
	public Integer getMenuId() {
		return menuId;
	}
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}
	public Integer getMotherMenuId() {
		return motherMenuId;
	}
	public void setMotherMenuId(Integer motherMenuId) {
		this.motherMenuId = motherMenuId;
	}
	public String getMenuNm() {
		return menuNm;
	}
	public void setMenuNm(String menuNm) {
		this.menuNm = menuNm;
	}
	public String getMenuCode() {
		return menuCode;
	}
	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

}